services:
  # Backend API Service
  - type: web
    name: analytics-backend
    env: node
    buildCommand: cd Back-End && npm install
    startCommand: cd Back-End && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080

  # Frontend Static Site
  - type: web
    name: analytics-dashboard
    env: static
    buildCommand: cd dashboard-ui && npm install && npm run build
    staticPublishPath: ./dashboard-ui/dist
    envVars:
      - key: NODE_VERSION
        value: 20.0.0 