name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dashboard-ui

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './dashboard-ui/package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build Frontend
      run: npm run build
    
    - name: Upload Frontend Build
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: dashboard-ui/dist

  build-and-test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Back-End

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './Back-End/package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Upload Backend Files
      uses: actions/upload-artifact@v4
      with:
        name: backend-files
        path: Back-End/

  deploy:
    needs: [build-and-test-frontend, build-and-test-backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download Frontend Build
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend-build

    - name: Download Backend Files
      uses: actions/download-artifact@v4
      with:
        name: backend-files
        path: backend-files

    # Deploy to GitHub Pages (Frontend)
    - name: Deploy Frontend to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend-build
        
    # Deploy Backend (example using Heroku)
    - name: Deploy Backend to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "backend-files" 